In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/insurance (1).csv")

In [ ]:
df

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

Calculate the mean charges for smokers who are also obese (BMI greater than or equal to 30) and have at least 2 children

In [ ]:
df[(df.smoker=='yes')&(df.bmi>=30)&(df.children>=2)]['charges'].mean()

42358.52335166667

Calculate the standard deviation of charges for non-smokers with a BMI between 25 and 30 who have no children.

In [ ]:
df[(df.smoker=='no')&((df.bmi>=25)|(df.bmi<=30))&(df.children==0)]['charges'].std()

5858.529188602178

Perform a t-test to determine if there is a significant difference in charges between smokers and non-smokers who are also obese (BMI greater than or equal to 30)

In [ ]:
import scipy.stats as st

In [ ]:
smoke=df[(df.smoker=='yes')&(df.bmi>=30)]['charges']

In [ ]:
nsmoke=df[(df.smoker=='no')&(df.bmi>=30)]['charges']

In [ ]:
stat,p_=st.ttest_ind(smoke,nsmoke)

In [ ]:
p_

3.8432580014532043e-269

In [ ]:
if p_>0.05:
  print("similar")
else:
  print("non similar")

non similar

Calculate the correlation coefficient between BMI and charges separately for males and females. Is there a significant difference in the correlation between the two groups?

In [ ]:
sdf=df[df['sex']=='male']
print(sdf['bmi'].corr(sdf['charges']))

0.2258470799925905

In [ ]:
sdf=df[df['sex']=='female']
print(sdf['bmi'].corr(sdf['charges']))

0.16141865039818795


Calculate the median charges for individuals in the northeast region who are non-smokers and have no children, but only for those whose BMI is in the top 25% of the dataset.

In [ ]:
sd=df[df['bmi']>df['bmi'].quantile(0.75)]
sd

      age     sex     bmi  children smoker     region      charges
13     56  female  39.820         0     no  southeast  11090.71780
14     27    male  42.130         0    yes  southeast  39611.75770
18     56    male  40.300         0     no  southwest  10602.38500
19     30    male  35.300         0    yes  southwest  36837.46700
20     60  female  36.005         0     no  northeast  13228.84695
...   ...     ...     ...       ...    ...        ...          ...
1322   62    male  38.830         0     no  southeast  12981.34570
1323   42  female  40.370         2    yes  southeast  43896.37630
1329   52    male  38.600         2     no  southwest  10325.20600
1332   52  female  44.700         3     no  southwest  11411.68500
1335   18  female  36.850         0     no  southeast   1629.83350

[335 rows x 7 columns]

In [ ]:
sd[(sd['region']=='northeast')&(sd['smoker']=='no')&(sd['children']==0)]['charges'].median()

11566.30055

Perform a chi-squared test to determine if there is a significant relationship between smoker status and region, but only for individuals with a BMI greater than or equal to 25.

In [ ]:
sdf=df[df['bmi']>25]

In [ ]:
sd=sdf[['smoker','region']]

In [ ]:
tab=pd.crosstab(sd.region,sd.smoker)
tab

smoker      no  yes
region
northeast  196   45
northwest  209   46
southeast  246   77
southwest  221   51

In [ ]:
a,b,c,d=st.chi2_contingency(tab)

In [ ]:
b

0.25042750301375916

In [ ]:
if b>0.05:
  print("no significant")
else:
  print('significant ')

no significant


Check the normality of the Charges column by using the Shapiro-Wilk test. If it is a normal distribution provide an answer as “Normal Distribution” else provide the answer as ”Not A Normal Distribution”.

In [ ]:
w,p=st.shapiro(df['charges'])

In [ ]:
p

1.1505194006561963e-36

In [ ]:
if p>0.05:
  print("Normal Distribution")
else:
  print('Not A Normal Distribution')

Not A Normal Distribution

Find the confidence interval for the mean of the age column. Only provide the lower limit of the interval rounded up to 2 decimal places.

Calculate the Standard Error for the charges column. (Round up the final answer to 2 decimal places.)

In [ ]:
round(st.sem(df['charges']),2)

331.07


Check the normality of the BMI column by using the Shapiro-Wilk test. If it is a normal distribution provide an answer as “Normal Distribution” else provide the answer as ”Not A Normal Distribution”.

In [ ]:
s,p=st.shapiro(df['bmi'])

In [ ]:
p

2.6033414542325772e-05

In [ ]:
if p>0.05:
  print("Normal Distribution")
else:
  print('Not A Normal Distribution')

Not A Normal Distribution

NameError: ignored